### ISSUE TITLE
problem support utf-8

### ISSUE THREAD

**Issue by xlmnxp** [ybulach/MyWebRSS#10]
not support arabic langauge . 
Arabic letters turn into a "?"

![xcga0az](https://cloud.githubusercontent.com/assets/14010451/14837022/8eb0191e-0c1d-11e6-83ce-cccbecb7711e.png)

**Comment by ybulach** [comment]
This issue most likely come from the MyWebRSS-API (separate repository), which is discontinued due to the incoming end of support of Mozilla Persona authentication (see: https://www.persona.org/).
