### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JKingweb** [ybulach/MyWebRSS#12]
I'd be interested in perhaps cleaning up MyWebRSS to use it as a Web-based client for my headless RSS sync server. However, no license is provided, which makes me or anyone else legally incapable of doing anything with it. Could you please add a license to clarify which flavour of "open source" you had intended?

**Comment by ybulach** [comment]
License has been added, and project marked as "discontinued" in commit 1c00fa3a308d5f32a1aad502969e5639617dfb23.
