### ISSUE TITLE
App not wokrking with ownCloud 8

### ISSUE THREAD

**Issue by monreal** [ybulach/MyWebRSS#9]
I use ownCloud News on my ownCloud 8.0.2 installation. I installed MyWebRSS on desktop and android firefox as well as the Firefox OS simulator but can not get it to work either way (now feeds showing up) after adding the API.

Is ownCloud 8 supported? If so, how can I debug the problem? If you want to check against my server I could set up a test account for you.

**Comment by monreal** [comment]
I found the following using the semulator's debugger:

"Please select a valid API first" "
    at StatusView<.setMessage (http://html5.mywebrss.net/js/app/views/Status.js:14:3)" Status.js:14:3

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at <MY SERVER>/index.php/apps/news/api/v1-2/items?batchSize=20&offset=0&type=3&id=0&getRead=false. This can be fixed by moving the resource to the same domain or enabling CORS. items

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**Comment by ybulach** [comment]
As show by the log, this seems to be a result of disabled Cross-Origin on your ownCloud installation.

If you are using Apache2, can you try to add this in a htaccess (mod_headers is needed):
Header set Access-Control-Allow-Origin "*"

**Comment by monreal** [comment]
I am really confused. The app code seems to be loaded from html5.mywebrss.net and does not have the Access-Control-Allow-Origin header. I added the header to my ownCloud but it did not change anything.

To me it looks like the problem is on the html5.mywebrss.net side as the error message says "disallows reading the remote resource" where the remote resource is my server?

**Comment by ybulach** [comment]
html5.mywebrss.net only serves HTML/CSS/JS. The browser is the one that execute the JS. The server is the only one that can allow or not an origin to access his resources with AJAX.

I've tested ownCloud 8.0.2, with News 5.2.8 and it worked like a charm. Although, the `Access-Control-Allow-Origin` is not necessary as it seems to be added by PHP.

Can you send your URL and a test account to postmaster [at] mywebrss.net for more tests, as i didn't reproduce your problem ?

**Comment by monreal** [comment]
Thanks a lot for explaining. I actually took the time to read into WebApps and CORS last night and got a basic understanding. 

I experimented with some headers and even installed mywebrss on my own Server (different sublevel, so still not "sameorigin") and it first worked when used directly in desktop Firefox. However I still could not get to Firefox in the simulator. Same thing with using html5.mywebrss.net on the desktop directly VS passing it as a hosted app into the simulator. As some point I ran into my own mywebrss installation also not working on the desktop (same "Cross-Origin Request Blocked" error as in the simulator) but after deleting and re-adding the API it works again. I have re-added the API on the simulator many times but it never worked there (version 2.0 as well as 2.2).

Now I also get "[ERROR] OwnCloud News API<br/>[object XMLHttpRequest]" which I guess is caused by the latest commit.

I sent you a test account.

**Comment by ybulach** [comment]
Just done more tests and the CORS seems to work fine.

The `[object XMLHttpRequest]` error indicates that a non JSON (in this case HTML) content has been returned. This can be:

- server sending a 404/403/500 error page (a quick fix has been done for this: d1af6c1c3c3e448639ea0ba96381d365147e28fa)
- navigator showing a warning page (self-signed certificate or unknown CA)

For this second choice, you need to add an exception on your navigator by accessing your ownCloud installation. In FirefoxOS (in the simulator as well), you can access it inside the browser, and the webapps will use the same exception list.

**Comment by monreal** [comment]
After visiting the page using the FxOS browser and approving the exception the app seems to work fine. I still don't know why I ran into the problem on my desktop firefox (which has the CA cert installed) once.
